import express from 'express';
import helmet from 'helmet';
import QRCode from 'qrcode';
import path from 'path';
import {fileURLToPath} from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const app=express();const port=Number(process.env.PORT||3000);
app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));
app.get('/health',(_req,res)=>res.json({ok:true,mode:'local-admin'}));
app.get('/api/qr',async(req,res)=>{try{const upi=String(req.query.upi||''),name=String(req.query.name||'Video Selling'),amount=Number(req.query.amount||0);if(!upi||!amount)return res.status(400).send('UPI and amount are required.');const uri=`upi://pay?pa=${encodeURIComponent(upi)}&pn=${encodeURIComponent(name)}&am=${encodeURIComponent(amount.toFixed(2))}&cu=INR`;res.type('png').set('Cache-Control','no-store').send(await QRCode.toBuffer(uri,{type:'png',width:480,margin:2,errorCorrectionLevel:'M'}))}catch{return res.status(500).send('Unable to generate QR.')}});
app.use(express.static(path.join(__dirname,'../public'),{extensions:['html']}));app.listen(port,()=>console.log(`Video Selling running on ${port}`));
