import express from 'express';import helmet from 'helmet';import QRCode from 'qrcode';import fs from 'fs';import path from 'path';import crypto from 'crypto';import {fileURLToPath} from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));const app=express();const port=Number(process.env.PORT||3000);const dataDir=process.env.DATA_DIR||path.join(__dirname,'../data');const dataFile=path.join(dataDir,'store.json');const adminPin=String(process.env.ADMIN_PIN||'1234');const sessions=new Set();
app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'2mb'}));
const seed=()=>({storeName:'Video Selling',upiId:'jaduuugarrr@okaxis',telegram:['ZzzNnnVvvv','Ramerusaan'],email:'',phone:'',supportHours:'Support available for order assistance.',announcement:'',refundSummary:'Digital purchases are generally final after successful delivery, subject to applicable law.',deliverySummary:'Digital access details are provided after payment confirmation.',packages:[['Prime Access',149,199,'POPULAR'],['Exclusive Access',249,299,'VALUE'],['VIP Access',299,399,'VIP'],['VIP Elite',349,449,'BEST VALUE'],['VVIP Access',399,499,'VVIP'],['VVIP Black',449,599,'BLACK'],['Ultra Elite',499,699,'ULTRA']].map((x,i)=>({id:'p'+(i+1),name:x[0],price:x[1],original_price:x[2],badge:x[3],description:'Digital access.',features:['Instant access','24×7 support'],active:true,sort_order:i+1})),groups:[],offers:[],orders:[],faqs:[],policies:{terms:'',refund:'',privacy:'',digitalGoods:''}});
function read(){try{return JSON.parse(fs.readFileSync(dataFile,'utf8'))}catch{const s=seed();try{fs.mkdirSync(dataDir,{recursive:true});fs.writeFileSync(dataFile,JSON.stringify(s,null,2))}catch{}return s}}function write(s){fs.mkdirSync(dataDir,{recursive:true});fs.writeFileSync(dataFile,JSON.stringify(s,null,2))}if(!fs.existsSync(dataFile))write(seed());
function auth(req,res,next){const t=req.get('authorization')?.replace(/^Bearer\s+/i,'');if(!t||!sessions.has(t))return res.status(401).json({error:'Unauthorized'});next()}
app.get('/health',(_q,r)=>r.json({ok:true,mode:'portable-admin'}));app.post('/api/admin/login',(q,r)=>{if(String(q.body?.pin||'')!==adminPin)return r.status(401).json({error:'Incorrect PIN'});const t=crypto.randomBytes(24).toString('hex');sessions.add(t);r.json({token:t})});app.post('/api/admin/logout',auth,(q,r)=>{sessions.delete(q.get('authorization').replace(/^Bearer\s+/i,''));r.json({ok:true})});app.get('/api/store',(_q,r)=>r.json(read()));app.get('/api/admin/store',auth,(_q,r)=>r.json(read()));
app.put('/api/admin/store',auth,(q,r)=>{const cur=read(),b=q.body||{},next={...cur,...b};for(const k of ['packages','groups','offers','orders','faqs'])if(!Array.isArray(b[k]))next[k]=cur[k];next.policies=b.policies||cur.policies;write(next);r.json(next)});
app.post('/api/orders',(q,r)=>{const s=read(),o=q.body||{};if(!String(o.customerName||'').trim()||!o.packageName||!Number(o.amount))return r.status(400).json({error:'Name, product and amount are required'});const order={id:o.id||'ORD-'+Date.now().toString(36).toUpperCase(),packageId:o.packageId||null,packageName:String(o.packageName),amount:Number(o.amount),customerName:String(o.customerName).trim(),status:'pending',createdAt:new Date().toISOString()};s.orders.unshift(order);write(s);r.status(201).json(order)});
app.get('/api/qr',async(q,r)=>{try{const upi=String(q.query.upi||''),name=String(q.query.name||'Video Selling'),amount=Number(q.query.amount||0);if(!upi||!amount)return r.status(400).send('UPI and amount are required.');const uri=`upi://pay?pa=${encodeURIComponent(upi)}&pn=${encodeURIComponent(name)}&am=${encodeURIComponent(amount.toFixed(2))}&cu=INR`;r.type('png').set('Cache-Control','no-store').send(await QRCode.toBuffer(uri,{type:'png',width:480,margin:2,errorCorrectionLevel:'M'}))}catch{return r.status(500).send('Unable to generate QR.')}});
app.use(express.static(path.join(__dirname,'../public'),{extensions:['html']}));
export default app;
if(process.env.VERCEL!=='1')app.listen(port,()=>console.log(`Video Selling running on ${port}`));
